#!/usr/bin/env python3
"""Propose roadmap deliverables from machine findings, idempotently.

Shared by every instrument that turns a finding into planned work — the landscape survey
and the supply chain audit today. Both write the grammar `roadmap_ingest.py` parses, so a
proposal ranks against defects in one prioritizer rather than accumulating in a second
list nobody reads.

Two properties matter more than the formatting:

* **Identity is a marker, not a title.** Each proposal carries `landscape-gap:...` or
  `supply-risk:...` written into the item, so re-wording a deliverable by hand does not
  make the next run add it again.
* **Value and effort are never invented.** A machine can establish that something is true;
  it cannot establish what fixing it is worth here. Proposals carry no prioritization
  matrix row, so the ingester ranks them on defaults and says so.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Final

DEFAULT_MILESTONE: Final[str] = "### Milestone 5:"
DEFAULT_PRIORITY: Final[str] = "P2 - Medium"


@dataclass(frozen=True)
class Proposal:
    """One deliverable a machine finding proposes, with the evidence that would falsify it."""

    marker: str
    title: str
    context: str
    evidence: str
    priority: str = DEFAULT_PRIORITY

    def render(self) -> list[str]:
        """Render as a roadmap deliverable in the grammar `roadmap_ingest.py` parses."""
        return [
            f"- [ ] **{self.title} ({self.priority})**:",
            f"  - *Finding*: {self.context}",
            f"  - *Evidence*: {self.evidence}",
            f"  - *Survey*: `{self.marker}` — regenerated by tooling; "
            "delete this bullet only with the item.",
        ]


def insert_proposals(
    roadmap_text: str, proposals: Sequence[Proposal], milestone: str = DEFAULT_MILESTONE
) -> tuple[str, list[str], list[str]]:
    """Insert proposals not already tracked, returning (text, added, skipped).

    An item already present — open, checked off, or hand-edited — is skipped. Tooling
    proposes work once; what happens to it afterwards is the roadmap's business.
    """
    added: list[str] = []
    skipped: list[str] = []
    pending: list[str] = []
    for proposal in proposals:
        if proposal.marker in roadmap_text:
            skipped.append(proposal.title)
            continue
        pending.extend(proposal.render())
        added.append(proposal.title)
    if not pending:
        return roadmap_text, added, skipped
    return _splice_into_milestone(roadmap_text, pending, milestone), added, skipped


def _splice_into_milestone(roadmap_text: str, block: Sequence[str], milestone: str) -> str:
    """Place a block at the end of the named milestone section."""
    lines = roadmap_text.splitlines()
    start = _milestone_index(lines, milestone)
    end = _section_end(lines, start)
    return "\n".join(lines[:end] + list(block) + lines[end:]) + "\n"


def _milestone_index(lines: Sequence[str], milestone: str) -> int:
    """Return the index of the milestone heading, or raise naming what was searched for."""
    for index, line in enumerate(lines):
        if line.startswith(milestone):
            return index
    raise ValueError(f"No milestone heading starting with {milestone!r} in the roadmap")


def _section_end(lines: Sequence[str], start: int) -> int:
    """Return the index just past the last content line of the section beginning at `start`."""
    end = start + 1
    for index in range(start + 1, len(lines)):
        if lines[index].startswith(("### ", "## ", "---")):
            break
        if lines[index].strip():
            end = index + 1
    return end
